// Snowflake ID Generator
// Structure: timestamp (41 bits) | worker (10 bits) | sequence (12 bits) = 63 bits
// Similar to Twitter's Snowflake ID implementation

const EPOCH = 1288834974657n; // Custom epoch (Nov 4, 2010 in milliseconds)
const WORKER_ID_BITS = 10n;
const SEQUENCE_BITS = 12n;
const MAX_WORKER_ID = (1n << WORKER_ID_BITS) - 1n;
const MAX_SEQUENCE = (1n << SEQUENCE_BITS) - 1n;

let lastTimestamp = -1n;
let workerId = 1n; // Default worker ID
let sequence = 0n;

/**
 * Set the worker ID for this instance
 * Worker ID helps differentiate IDs generated by different servers/instances
 */
export function setWorkerId(id: number) {
  if (id < 0 || id > Number(MAX_WORKER_ID)) {
    throw new Error(
      `Worker ID must be between 0 and ${MAX_WORKER_ID}`
    )
  }
  workerId = BigInt(id)
}

/**
 * Generate a Snowflake ID
 * Returns a BigInt that can be stored in a bigint PostgreSQL column
 */
export function generateId(): bigint {
  let now = BigInt(Date.now());

  if (now === lastTimestamp) {
    sequence = (sequence + 1n) & MAX_SEQUENCE;
    if (sequence === 0n) {
      // Sequence overflow, wait for next millisecond
      while (now <= lastTimestamp) {
        now = BigInt(Date.now());
      }
    }
  } else {
    sequence = 0n;
  }

  lastTimestamp = now;

  const timestamp = (now - EPOCH) << (WORKER_ID_BITS + SEQUENCE_BITS);
  const worker = workerId << SEQUENCE_BITS;
  const id = timestamp | worker | sequence;

  return id;
}

/**
 * Parse a Snowflake ID to extract timestamp, worker ID, and sequence
 */
export function parseId(id: bigint) {
  const timestamp = new Date(
    Number((id >> (WORKER_ID_BITS + SEQUENCE_BITS)) + EPOCH)
  );
  const worker = Number((id >> SEQUENCE_BITS) & MAX_WORKER_ID);
  const seq = Number(id & MAX_SEQUENCE);

  return {
    timestamp,
    workerId: worker,
    sequence: seq,
  };
}

/**
 * Get the timestamp from a Snowflake ID
 */
export function getTimestamp(id: bigint): Date {
  return new Date(Number((id >> (WORKER_ID_BITS + SEQUENCE_BITS)) + EPOCH));
}

/**
 * Sort Snowflake IDs in chronological order
 * Lower IDs are older, higher IDs are newer
 */
export function compare(id1: bigint, id2: bigint): number {
  if (id1 < id2) return -1;
  if (id1 > id2) return 1;
  return 0;
}

// Export an object with methods for use in templates if needed
export const snowflake = {
  generateId,
  parseId,
  getTimestamp,
  compare,
  setWorkerId,
};

